# Manual Training Loop

Goal: understand what happens during neural-network training by manually training a tiny model.

We will learn a simple relationship:

y = 3x + 2

and watch PyTorch adjust a weight and bias using gradients.

In [8]:
# simple training data

import torch

x = torch.tensor([
    [1.0],
    [2.0],
    [3.0],
    [4.0],
    [5.0]
])

y = 3 * x + 2  #y = 3x + 2, behind the scenes we know weights = 3 and bias = 2

print("x:\n", x)
print("\ny:\n", y)

x:
 tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.]])

y:
 tensor([[ 5.],
        [ 8.],
        [11.],
        [14.],
        [17.]])


In [9]:
# intentionally incorrect starting parameters for weights and bias

w = torch.tensor([[0.5]], requires_grad=True)  # requires_grad=True tells pytorch to track how calculations depend on w and b so that we can retrieve their gradients
b = torch.tensor([0.0], requires_grad=True) # these parameters w and b are the trainable parameters of our model, and we will update them during training to minimize the loss function

print("Starting weight:", w.item())
print("Starting bias:", b.item())

Starting weight: 0.5
Starting bias: 0.0


In [10]:
# manual predictions

predictions = x @ w + b  # yhat = x @ w + b, where @ is the matrix multiplication operator in pytorch

print(predictions)

tensor([[0.5000],
        [1.0000],
        [1.5000],
        [2.0000],
        [2.5000]], grad_fn=<AddBackward0>)


In [11]:
# loss calculation

loss = ((predictions - y) ** 2).mean()

print("Loss:", loss.item())

Loss: 102.75


In [12]:
loss.backward() 

# loss function moves backwards through the chain
# gradient values tell the direction and magnitude w and b should move to in order to reduce loss

print("Gradient for w:", w.grad)
print("Gradient for b:", b.grad)

Gradient for w: tensor([[-67.]])
Gradient for b: tensor([-19.])


In [15]:
# manual gradient descent update (once)

learning_rate = 0.01

with torch.no_grad():
    w -= learning_rate * w.grad
    b -= learning_rate * b.grad

print("Updated weight:", w.item())
print("Updated bias:", b.item())

Updated weight: 2.5099997520446777
Updated bias: 0.5699999928474426


In [17]:
# clear gradients (pytorch accumulates gradients)
# if we dont clear gradients the next backward() will add new gradients to old ones
# real pytorch training loops use optimizer.zero_grad() for this

w.grad.zero_()
b.grad.zero_()

tensor([0.])