In [1]:
# tool import and test
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

PyTorch version: 2.14.0+cu130
CUDA available: True


In [2]:
scalar = torch.tensor(7) # a scalar tensor, one row, one column
vector = torch.tensor([1, 2, 3]) # a vector tensor, one row, three columns
matrix = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
]) # a matrix tensor

#row = observations, column = features

print("scalar:", scalar)
print("vector:", vector)
print("matrix:\n", matrix)

scalar: tensor(7)
vector: tensor([1, 2, 3])
matrix:
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
print("scalar ndim:", scalar.ndim)
print("vector ndim:", vector.ndim)
print("matrix ndim:", matrix.ndim)

print("scalar shape:", scalar.shape)
print("vector shape:", vector.shape)
print("matrix shape:", matrix.shape)

scalar ndim: 0
vector ndim: 1
matrix ndim: 2
scalar shape: torch.Size([])
vector shape: torch.Size([3])
matrix shape: torch.Size([2, 3])


In [4]:
# tensor dtypes
int_tensor = torch.tensor([1, 2, 3])
float_tensor = torch.tensor([1.0, 2.0, 3.0])

print("int_tensor:", int_tensor)
print("dtype:", int_tensor.dtype)

print()

print("float_tensor:", float_tensor)
print("dtype:", float_tensor.dtype)

int_tensor: tensor([1, 2, 3])
dtype: torch.int64

float_tensor: tensor([1., 2., 3.])
dtype: torch.float32


In [5]:
x = torch.tensor(
    [1, 2, 3],
    dtype=torch.float32
)

print(x)
print(x.dtype)

tensor([1., 2., 3.])
torch.float32


In [6]:
x = torch.tensor([1, 2, 3])

print(x)
print(x.dtype)

x_float = x.float()

print(x_float)
print(x_float.dtype)

# or x_float = x.to(torch.float32)

tensor([1, 2, 3])
torch.int64
tensor([1., 2., 3.])
torch.float32


In [7]:
# tensor indexing
x = torch.tensor([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(x)
print("shape:", x.shape)

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
shape: torch.Size([3, 3])


# Retrieving Values

In [8]:
# first row retrieval
x[0]

tensor([10, 20, 30])

In [9]:
# second row retrieval
x[1]

tensor([40, 50, 60])

In [10]:
# individual value retrieve
x[0, 0]

tensor(10)

In [11]:
x[1, 2]

tensor(60)

In [13]:
# slicing
x[:,0] # all rows, first column

tensor([10, 40, 70])

In [14]:
x[:,1] # all rows, second column

tensor([20, 50, 80])

In [16]:
x[:,:] # all rows, all columns

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

## Basic Tensor Math

In [17]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

In [18]:
# addition
a + b

tensor([5., 7., 9.])

In [19]:
# subtraction
a - b

tensor([-3., -3., -3.])

In [20]:
# element wise multiplication
a * b

tensor([ 4., 10., 18.])

In [21]:
# element wise division
a / b

tensor([0.2500, 0.4000, 0.5000])

# matrix multiplication

In [22]:
A = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0]
])

B = torch.tensor([
    [5.0, 6.0],
    [7.0, 8.0]
])

In [24]:
A @ B # matrix multiplication

tensor([[19., 22.],
        [43., 50.]])

In [26]:
torch.matmul(A, B) # also matrix multiplication

tensor([[19., 22.],
        [43., 50.]])