In [1]:
# tool import and test
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

PyTorch version: 2.14.0+cu130
CUDA available: True


In [2]:
scalar = torch.tensor(7) # a scalar tensor, one row, one column
vector = torch.tensor([1, 2, 3]) # a vector tensor, one row, three columns
matrix = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
]) # a matrix tensor

#row = observations, column = features

print("scalar:", scalar)
print("vector:", vector)
print("matrix:\n", matrix)

scalar: tensor(7)
vector: tensor([1, 2, 3])
matrix:
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
print("scalar ndim:", scalar.ndim)
print("vector ndim:", vector.ndim)
print("matrix ndim:", matrix.ndim)

print("scalar shape:", scalar.shape)
print("vector shape:", vector.shape)
print("matrix shape:", matrix.shape)

scalar ndim: 0
vector ndim: 1
matrix ndim: 2
scalar shape: torch.Size([])
vector shape: torch.Size([3])
matrix shape: torch.Size([2, 3])


In [4]:
# tensor dtypes
int_tensor = torch.tensor([1, 2, 3])
float_tensor = torch.tensor([1.0, 2.0, 3.0])

print("int_tensor:", int_tensor)
print("dtype:", int_tensor.dtype)

print()

print("float_tensor:", float_tensor)
print("dtype:", float_tensor.dtype)

int_tensor: tensor([1, 2, 3])
dtype: torch.int64

float_tensor: tensor([1., 2., 3.])
dtype: torch.float32


In [5]:
x = torch.tensor(
    [1, 2, 3],
    dtype=torch.float32
)

print(x)
print(x.dtype)

tensor([1., 2., 3.])
torch.float32


In [7]:
x = torch.tensor([1, 2, 3])

print(x)
print(x.dtype)

x_float = x.float()

print(x_float)
print(x_float.dtype)

# or x_float = x.to(torch.float32)

tensor([1, 2, 3])
torch.int64
tensor([1., 2., 3.])
torch.float32


In [8]:
# tensor indexing
x = torch.tensor([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(x)
print("shape:", x.shape)

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
shape: torch.Size([3, 3])


In [10]:
# first row retrieval
x[0]

tensor([10, 20, 30])

In [12]:
# second row retrieval
x[1]

tensor([40, 50, 60])

In [14]:
# individual value retrieve
x[0, 0]

tensor(10)

In [15]:
x[1, 2]

tensor(60)