In [1]:
# tool import and test
import torch

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

PyTorch version: 2.14.0+cu130
CUDA available: True


In [2]:
scalar = torch.tensor(7) # a scalar tensor, one row, one column
vector = torch.tensor([1, 2, 3]) # a vector tensor, one row, three columns
matrix = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
]) # a matrix tensor

#row = observations, column = features

print("scalar:", scalar)
print("vector:", vector)
print("matrix:\n", matrix)

scalar: tensor(7)
vector: tensor([1, 2, 3])
matrix:
 tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
print("scalar ndim:", scalar.ndim)
print("vector ndim:", vector.ndim)
print("matrix ndim:", matrix.ndim)

print("scalar shape:", scalar.shape)
print("vector shape:", vector.shape)
print("matrix shape:", matrix.shape)

scalar ndim: 0
vector ndim: 1
matrix ndim: 2
scalar shape: torch.Size([])
vector shape: torch.Size([3])
matrix shape: torch.Size([2, 3])


In [4]:
# tensor dtypes
int_tensor = torch.tensor([1, 2, 3])
float_tensor = torch.tensor([1.0, 2.0, 3.0])

print("int_tensor:", int_tensor)
print("dtype:", int_tensor.dtype)

print()

print("float_tensor:", float_tensor)
print("dtype:", float_tensor.dtype)

int_tensor: tensor([1, 2, 3])
dtype: torch.int64

float_tensor: tensor([1., 2., 3.])
dtype: torch.float32


In [5]:
x = torch.tensor(
    [1, 2, 3],
    dtype=torch.float32
)

print(x)
print(x.dtype)

tensor([1., 2., 3.])
torch.float32


In [6]:
x = torch.tensor([1, 2, 3])

print(x)
print(x.dtype)

x_float = x.float()

print(x_float)
print(x_float.dtype)

# or x_float = x.to(torch.float32)

tensor([1, 2, 3])
torch.int64
tensor([1., 2., 3.])
torch.float32


In [7]:
# tensor indexing
x = torch.tensor([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print(x)
print("shape:", x.shape)

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])
shape: torch.Size([3, 3])


# Retrieving Values

In [8]:
# first row retrieval
x[0]

tensor([10, 20, 30])

In [9]:
# second row retrieval
x[1]

tensor([40, 50, 60])

In [29]:
# individual value retrieve
x[0, 0] # first row, first column = first observation, first feature

tensor(10)

In [30]:
x[1, 2] # second row, third column = second observation, third feature

tensor(60)

In [12]:
# slicing
x[:,0] # all rows, first column

tensor([10, 40, 70])

In [13]:
x[:,1] # all rows, second column

tensor([20, 50, 80])

In [14]:
x[:,:] # all rows, all columns

tensor([[10, 20, 30],
        [40, 50, 60],
        [70, 80, 90]])

## Basic Tensor Math

In [15]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

In [16]:
# addition
a + b

tensor([5., 7., 9.])

In [17]:
# subtraction
a - b

tensor([-3., -3., -3.])

In [31]:
# element wise multiplication, this is not matrix multiplication
a * b

tensor([ 4., 10., 18.])

In [19]:
# element wise division
a / b

tensor([0.2500, 0.4000, 0.5000])

# matrix multiplication

In [20]:
A = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0]
])

B = torch.tensor([
    [5.0, 6.0],
    [7.0, 8.0]
])

In [21]:
A @ B # matrix multiplication

tensor([[19., 22.],
        [43., 50.]])

In [22]:
torch.matmul(A, B) # also matrix multiplication

tensor([[19., 22.],
        [43., 50.]])

In [23]:
# fundamental neural-network layer operations may look like:
# X = input batch tensor
# W = weight matrix
# b = bias
# XW + b
# where output is the transformed tensor

# The Shape Rule

In [24]:
X = torch.randn(512, 30) # 512 observations, 30 input features
W = torch.randn(30, 64) # layers weight matrix with 64 neurons

output = X @ W # Matrix multiplication gives 512 observations and 64 learned features

print("X shape:", X.shape)
print("W shape:", W.shape)
print("Output shape:", output.shape)

X shape: torch.Size([512, 30])
W shape: torch.Size([30, 64])
Output shape: torch.Size([512, 64])


In [25]:
# pytorch packages (same thing as above)
layer = torch.nn.Linear(30,64)

output = layer(X)

output.shape

torch.Size([512, 64])

In [26]:
torch.nn.Linear(64,32) # another layer

Linear(in_features=64, out_features=32, bias=True)

In [27]:
torch.nn.Linear(32,1) # final regression layer

Linear(in_features=32, out_features=1, bias=True)

In [28]:
#    [512, 30]
#        ↓
#    30 real input features

#    [512, 64]
#        ↓
#    64 learned representations

#    [512, 32]
#        ↓
#    32 deeper learned representations

#    [512, 1]
#        ↓
#    1 prediction per observation

# Moving tensors from CPU to GPU

In [34]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu") # checking for cuda device (gpu)

print("Using device:", device)

Using device: cuda


In [35]:
x = torch.randn(512, 30) # creating a CPU tensor

print("x device:", x.device)
print("x shape:", x.shape)

x device: cpu
x shape: torch.Size([512, 30])


In [36]:
x_gpu = x.to(device) # moving tensor to "device" which was previosly defined as gpu cuda device

print("x_gpu device:", x_gpu.device)
print("x_gpu shape:", x_gpu.shape)

x_gpu device: cuda:0
x_gpu shape: torch.Size([512, 30])


In [37]:
W = torch.randn(30, 64, device=device) # W weights to gpu device

print("W device:", W.device)
print("W shape:", W.shape)

W device: cuda:0
W shape: torch.Size([30, 64])


In [40]:
output = x_gpu @ W # matrix multiplication on gpu!

print("Output shape:", output.shape)
print("Output device:", output.device)

Output shape: torch.Size([512, 64])
Output device: cuda:0


In [41]:
# reminder that all tensors in deep learning operations need to be on either CPU or GPU
# cannot have one tensor on CPU and one on GPU

# example
cpu_tensor = torch.randn(512, 30)
gpu_weights = torch.randn(30, 64, device=device)

cpu_tensor @ gpu_weights # not on same chip, matrix multiplication attempt

RuntimeError: Expected all tensors to be on the same device, but got mat2 is on cuda:0, different from other tensors on cpu (when checking argument in method wrapper_CUDA_mm)